version: '3.9'

services:
  db:
    container_name: chat_db
    image: postgres:15.4-bookworm
    volumes:
      - /home/simon/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_chat_app
    command: ["/fastapi_chat_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  pgadmin:
    container_name: chat_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
     - "5050:80"
